import React, { useState } from 'react';
import type { GeneratedQuestion } from '../types';
import { QuestionDisplay } from './QuestionDisplay';
import { exportToDocx } from '../services/docxService';
import { QuizMode } from './QuizMode';
import type { User } from 'firebase/auth';
import { useTranslation } from 'react-i18next';

interface QuestionListProps {
  questions: GeneratedQuestion[];
  isQuizMode: boolean;
  setQuizMode: (mode: boolean) => void;
  user: User;
}

export const QuestionList: React.FC<QuestionListProps> = ({ questions, isQuizMode, setQuizMode, user }) => {
  const { t } = useTranslation();
  const [isExporting, setIsExporting] = useState(false);
  const [isSharing, setIsSharing] = useState(false);

  const handleExport = async () => {
    try {
        setIsExporting(true);
        await exportToDocx(questions);
    } catch (error) {
        console.error("Failed to export docx", error);
        alert(t('results.error_export'));
    } finally {
        setIsExporting(false);
    }
  };

  const handleShare = async () => {
      setIsSharing(true);
      const title = t('results.share_title');
      const count = questions.length;
      let content = `${title}\nSố lượng: ${count} câu\n\n`;
      
      questions.forEach((q, i) => {
          content += `Câu ${i+1}: ${q.question}\n`;
          if (q.options && q.options.length > 0) {
              q.options.forEach(opt => content += `${opt}\n`);
          }
          content += `\n`;
      });
      
      content += `Generated by BioGen AI`;
      
      try {
          await navigator.clipboard.writeText(content);
          alert(t('results.share_success'));
      } catch (err) {
          console.error("Share failed", err);
      } finally {
          setIsSharing(false);
      }
  };

  if (!questions || questions.length === 0) {
    return (
      <div className="text-center text-slate-500 dark:text-slate-400 flex-grow flex items-center justify-center p-10">
        <div className="max-w-sm">
            <p className="text-lg mb-2">{t('results.no_data')}</p>
            <p className="text-sm opacity-80">{t('results.no_data_desc')}</p>
        </div>
      </div>
    );
  }

  if (isQuizMode) {
      return <QuizMode questions={questions} onExit={() => setQuizMode(false)} user={user} />;
  }

  return (
    <div className="h-full flex flex-col">
       <div className="flex flex-col md:flex-row items-start md:items-center justify-between mb-6 px-1 gap-4">
          <h2 className="text-xl md:text-2xl font-bold text-slate-800 dark:text-white flex items-center gap-2">
            <span className="bg-gradient-to-r from-sky-500 to-blue-600 w-1.5 h-6 rounded-full"></span>
            {t('results.title')}
          </h2>
          
          <div className="flex items-center gap-3 flex-wrap">
             <span className="text-xs font-bold text-slate-600 dark:text-slate-300 bg-slate-100 dark:bg-slate-800 px-3 py-2 rounded-lg border border-slate-200 dark:border-slate-700">
                {questions.length} {t('results.count_suffix')}
             </span>
             
             {/* SHARE BUTTON */}
             <button
                onClick={handleShare}
                className="flex items-center gap-2 px-4 py-2 bg-pink-600 hover:bg-pink-700 text-white text-sm font-bold rounded-lg shadow-md shadow-pink-500/20 transition-all hover:scale-105"
             >
                 <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><line x1="8.59" x2="15.42" y1="13.51" y2="17.49"/><line x1="15.41" x2="8.59" y1="6.51" y2="10.49"/></svg>
                 {t('results.share')}
             </button>

             {/* START QUIZ BUTTON */}
             <button 
                onClick={() => setQuizMode(true)}
                className="flex items-center gap-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-bold rounded-lg shadow-md shadow-indigo-500/20 transition-all hover:scale-105"
             >
                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m12 14 7.472-4.981a.464.464 0 0 1 .687.56l-2.894 8.268a.464.464 0 0 1-.88 0l-2.894-8.268a.464.464 0 0 1 .687-.56L12 14Zm0 0V3"/></svg>
                {t('results.start_quiz')}
             </button>

             {/* EXPORT DOCX BUTTON (RESTORED) */}
             <button 
                onClick={handleExport}
                disabled={isExporting}
                className="flex items-center gap-2 px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white text-sm font-bold rounded-lg shadow-md shadow-emerald-500/20 transition-all hover:scale-105 disabled:opacity-70 disabled:cursor-not-allowed disabled:transform-none"
             >
                {isExporting ? (
                    <svg className="animate-spin h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>
                ) : (
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" x2="12" y1="15" y2="3"/></svg>
                )}
                {t('results.export_docx')}
             </button>
          </div>
       </div>

       <div className="space-y-6 overflow-y-auto pr-2 pb-4 flex-grow custom-scrollbar">
        {questions.map((q, index) => (
            <QuestionDisplay key={index} question={q} index={index + 1} />
        ))}
       </div>
    </div>
  );
};
